name: 'Update case counts data'

on:
  schedule:
    - cron: '0 8 * * *'

  repository_dispatch:
    types: update-case-counts-data

jobs:
  update-data:
    runs-on: ubuntu-20.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: update-case-counts-data
        run: |
          set -x

          PATH="$HOME/.local/bin:$PWD/node_modules/.bin:$PATH"

          python3 -m pip install --upgrade pip setuptools pipenv

          yarn install
          yarn schema:totypes

          cd data
          pipenv sync

          pipenv run python generate_data.py --fetch
          pipenv run python generate_data.py --output-cases ../src/assets/data/caseCounts.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: chore/update-case-counts
          title: 'Update case counts data'
          body: |
            Update case counts data
            - update case count tsv files
            - update case count json
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
